import asyncio
import json
import re
import os
import edge_tts
from mutagen.mp3 import MP3

VOZ_SELECIONADA = "pt-BR-FranciscaNeural"

PARAGRAFOS = [
  "<strong>Apresentação do Módulo 1</strong>",
  "Seja muito bem-vindo ao Módulo um, Epistemologia e Vida, a porta de entrada para a sua jornada de estudos em comportamento humano. Na aba de Introdução, você encontrará vinte e um pontos conceituais de extrema importância, cuidadosamente organizados para construir uma base sólida sobre o ciclo vital. Esse conteúdo foi estruturado para que você compreenda as engrenagens biológicas e sociais de maneira sequencial e didática ao iniciar seus estudos.",
  "Logo adiante, a aba de Análise oferece uma imersão profunda por meio de cinco tópicos integradores. Nessa seção, você investigará a dinâmica dos processos e as mecânicas de causa e efeito de nossas ações, além de conhecer o caso que evidencia empiricamente as limitações da métrica do Produto Interno Bruto e valida o paradigma do PNUD de 1990. Por fim, um estudo unificador amarra todo esse conteúdo, traduzindo as principais teorias em ferramentas úteis para a prática profissional.",
  "Na terceira aba, apresentamos três recursos gráficos interativos de apoio visual para facilitar a sua aprendizagem. O primeiro gráfico mapeia o Ecossistema de influências ambientais sobre o comportamento. O segundo consiste em uma Linha do Tempo detalhada das fases de desenvolvimento biológico e cognitivo do ciclo vital. O terceiro aborda as Perspectivas Teóricas e funciona como um filtro científico com correntes conceituais clássicas.",
  "Para consolidar todo o aprendizado de forma prática, a aba final disponibiliza um Quiz estruturado com trinta questões alternativas. Ao resolver os exercícios propostos, você poderá fixar com precisão cada conceito estudado no Módulo um, revisando seus acertos e erros de maneira produtiva e dinâmica no ambiente virtual. Esperamos sinceramente que você aproveite e desfrute ao máximo esta excelente experiência de aprendizado enriquecedora.",
  "<strong>1- Processos de Mudança e Estabilidade</strong>",
  "No cerne do estudo do desenvolvimento humano, encontra-se a investigação de duas forças dialéticas que operam de modo contínuo ao longo do tempo: aquilo que se transforma e aquilo que permanece constante no indivíduo. As transformações correspondem aos processos de mudança, manifestando-se de forma quantitativa, com alterações numéricas e de escala, como o ganho de peso, o crescimento físico e a expansão mensurável do vocabulário do sujeito.",
  "Por outro lado, as transformações qualitativas envolvem saltos estruturais complexos e de natureza profunda na cognição do indivíduo, como a transição do pensamento puramente concreto para o raciocínio lógico abstrato. Em contrapartida, aquilo que resiste ao tempo e se mantém fixo define a estabilidade, comumente expressa pela permanência de traços de personalidade e temperamento básicos do sujeito ao longo dos anos existenciais de sua vida.",
  "No campo prático das avaliações do comportamento humano, essa conceituação clássica serve como a régua de medição fundamental para o analista. Ela fornece a base técnica indispensável para diagnosticar se uma crise comportamental manifestada por um indivíduo reflete um padrão fixo e estruturado de sua personalidade, ou se representa apenas uma oscilação típica de uma fase de desenvolvimento. Referência: Livro: Capítulo 1.",
  "<strong>2- Dimensões do Desenvolvimento</strong>",
  "O desenvolvimento humano se manifesta de forma integrada por meio de frentes que a ciência divide didaticamente para fins de estudo acadêmico, mas que operam juntas na realidade concreta. Essas frentes são representadas pelas esferas física, cognitiva e psicossocial, formando dimensões indissociáveis do sujeito. A dimensão física compreende o crescimento do corpo, o amadurecimento do sistema nervoso, o controle motor e as condições de saúde.",
  "Por sua vez, a dimensão cognitiva abrange o fluxo de maturação de processos intelectuais superiores, tais como a memória recente e de longo prazo, a capacidade de atenção, o aprendizado linguístico e a resolução lógica de problemas cotidianos. Já a dimensão psicossocial envolve o desenvolvimento das emoções, a consolidação da personalidade e a calibração de comportamentos relacionais para a convivência do sujeito no seu meio social e familiar.",
  "Esta visão sistêmica e integrada ajuda a compreender o motivo pelo qual qualquer tipo de desgaste somático ou de sobrecarga em uma dimensão específica do sujeito repercute de forma imediata nas outras esferas existenciais. Na engenharia comportamental, percebe-se com clareza que um desajuste biológico persistente sabota a atividade do neocórtex e desorganiza o bem-estar emocional do indivíduo. Referência: Livro: Capítulo 1 / Aula 03.",
  "<strong>3- Períodos do Ciclo Vital</strong>",
  "A divisão do ciclo de vida em etapas bem definidas constitui uma construção social e cultural indispensável para que possamos organizar e compreender as transformações do ser humano ao longo do tempo cronológico. Essas fases se estendem desde o momento exato da concepção, passam pela primeira infância e pela adolescência, até alcançar a idade adulta tardia. Cada período é marcado por expectativas sociais e marcos biológicos característicos.",
  "No campo da análise comportamental aplicada, essa segmentação cronológica funciona como um instrumento valioso de contextualização clínica. Ela permite ao avaliador identificar se uma atitude do indivíduo está em harmonia com as expectativas de sua faixa etária, ou se representa um desvio que exige intervenção de suporte para restabelecer a agência pessoal e o desenvolvimento saudável do sujeito. Referência: Livro: Capítulo 1.",
  "<strong>4- Influências no Desenvolvimento (Hereditariedade, Ambiente e Maturação)</strong>",
  "O desenvolvimento humano é inteiramente moldado por uma teia complexa de forces biológicas, ambientais e de maturação que agem de forma combinada. A hereditariedade determina o patrimônio genético herdado diretamente dos pais biológicos do sujeito. Por sua vez, o ambiente engloba todas as experiências sociais e o meio físico no qual a pessoa vive e interage. Já a maturação biológica comanda o desdobramento natural dos padrões físicos do corpo.",
  "Na prática profissional da análise do comportamento, compreender a profunda interação dessas variáveis é indispensável para evitar visões reducionistas do ser humano. Esse mapeamento permite ao profissional identificar se uma conduta resulta de predisposições genéticas e maturacionais inerentes ao organismo, ou se ela é aprendida e mantida pelos estímulos e reforços presentes no contexto ambiental de convivência. Referência: Livro: Capítulo 1.",
  "<strong>5- Contextos do Desenvolvimento (Família, Vizinhança, Nível Socioeconômico, Cultura e Etnia)</strong>",
  "O indivíduo se desenvolve imerso em uma teia de contextos sociais e ecológicos que exercem impacto direto sobre suas atitudes e escolhas. A estrutura familiar, as características da vizinhança, o nível socioeconômico, os valores da cultura e a etnia formam o tecido social que molda as crenças, os hábitos e as oportunidades reais de agência do sujeito ao longo da vida, influenciando suas decisões de forma silenciosa e contínua.",
  "Para o avaliador comportamental, mapear esses cenários é fundamental para planejar intervenções eficazes. Conhecer a realidade financeira e o contexto de valores do indivíduo permite decodificar com clareza o significado de suas condutas. Isso possibilita a elaboração de orientações que façam sentido no cotidiano dele, respeitando as restrições materiais e aproveitando os recursos disponíveis em seu meio. Referência: Livro: Capítulo 1.",
  "<strong>6- Contexto Histórico (Coorte, Influências Normativas e Não-Normativas)</strong>",
  "O desenvolvimento humano é indissociável da época histórica em que ocorre, sendo influenciado por eventos coletivos e individuais. O conceito de coorte define o grupo de pessoas que compartilham experiências sociais por terem nascido no mesmo período. As influências normativas reguladas pela história, como crises econômicas e pandemias, impactam gerações, enquanto as não normativas são acontecimentos que afetam apenas um sujeito.",
  "Na prática da análise comportamental, compreender o peso da história é vital para contextualizar as atitudes do indivíduo de forma ampla. Esse diagnóstico evita que o profissional interprete reações típicas de uma coorte social, afetada por estresses coletivos de sua época, como desvios patológicos individuais de caráter. Isso possibilita desenhar suportes que respeitem a realidade histórica e as dores do sujeito no seu meio. Referência: Livro: Capítulo 1.",
  "<strong>7- Paul Baltes e a Perspectiva do Desenvolvimento ao Longo da Vida</strong>",
  "A abordagem científica de Paul Baltes estabelece que o desenvolvimento do ser humano é um processo contínuo que ocorre ao longo de toda a sua existência. Essa influente teoria postula que a evolução é multidimensional e multidirecional, ocorrendo de forma diversa em cada indivíduo. Ao longo de todo o ciclo de vida, o sujeito vivencia uma dinâmica constante de ganhos e perdas, em que o crescimento e o declínio biológico coexistem sempre.",
  "Para o avaliador comportamental, a perspectiva de Baltes oferece um mapa conceitual amplo para avaliar o potencial de mudança humana. Ao reconhecer a plasticidade de forma constante, o profissional evita o fatalismo clínico de julgar certas limitações como permanentes. Isso orienta a criação de intervenções dinâmicas que estimulam novas formas de agência e novos aprendizados em qualquer momento. Referência: Livro: Capítulo 1.",
  "<strong>8- Ontogênese e o Desenvolvimento Individual</strong>",
  "A ontogênese compreende todo o processo de desenvolvimento de um organismo individual ao longo do tempo. Ela descreve a trajetória biológica e psíquica que se estende desde o momento exato da concepção, atravessando as etapas de maturação cerebral e do sistema límbico, até o encerramento natural das funções vitais de Cronos. Esse percurso individual é influenciado por nossa carga biológica e pelas escolhas de agência de cada sujeito.",
  "Na prática clínica da análise comportamental, o real entendimento da ontogênese é indispensável para promover bem-estar. Compreender a inevitabilidade biológica do envelhecimento ajuda o profissional a apoiar o indivíduo no processo de aceitação saudável das mudanças corporais. Essa postura mitiga resistências desnecessárias, guiando o sujeito para o florescimento pleno de suas reais capacidades. Referência: Aula 03 / Aula 14.",
  "<strong>9- Perspectiva Psicanalítica</strong>",
  "A perspectiva psicanalítica, estruturada a partir dos modelos pioneiros de Sigmund Freud e expandida pelas ricas contribuições psicossociais de Erik Erikson, postula categoricamente que o comportamento humano manifesto é impulsionado, em grande parte, por forças latentes, impulsos intrínsecos e graves conflitos emocionais profundos que operam de forma contínua em nosso inconsciente ao longo de todo o ciclo vital humano.",
  "Sob essa ótica clínica, o desenvolvimento psíquico avança por meio de uma sucessão de estágios ou crises de identidade universais. Nesses momentos decisivos, o equilíbrio interno do sujeito depende da resolução satisfatória das tensões entre seus desejos internos primários e as barreiras ou exigências impostas pela realidade externa. Na prática analítica, essa abordagem é fundamental para identificar a origem de traumas infantis.",
  "Ao focar na esfera das emoções inconscientes e na influência determinante das primeiras relações parentais sobre a personalidade adulta, a psicanálise auxilia o sujeito a resgatar e a ressignificar memórias dolorosas que antes bloqueavam seu crescimento. Compreender essas dinâmicas profundas liberta o fluxo da vida e permite uma existência mais integrada e autêntica. Referência: Livro: Capítulo 1 / Aula 05.",
  "<strong>10- Perspectiva da Aprendizagem</strong>",
  "A perspectiva da aprendizagem, fundamentada nas sólidas bases do behaviorismo clássico e operante, bem como nas modernas teorias da aprendizagem social de Albert Bandura, defende que o desenvolvimento humano resulta do acúmulo contínuo de comportamentos observáveis e de reações aprendidas em constante interação com o meio ambiente.",
  "Ao contrário das teorias que priorizam processos internos abstratos, essa perspectiva se concentra nas leis universais de associação, reforço, punição e modelagem observacional direta. Sob esse prisma, o comportamento é moldado por meio de consequências diretas e pela imitação ativa de modelos sociais considerados relevantes pelo próprio sujeito.",
  "Na prática clínica e educacional, o entendimento dessas leis de aprendizagem permite estruturar contextos e ambientes altamente favoráveis à aquisição de novos hábitos e à eliminação de condutas desadaptativas. Ao transformar as contingências do meio, o sujeito reconquista o controle sobre sua própria trajetória evolutiva. Referência: Livro: Capítulo 1 / Aula 09 / Aula 12.",
  "<strong>11- Perspectiva Cognitiva</strong>",
  "A perspectiva cognitiva, inspirada nas incontornáveis obras de Jean Piaget e Lev Vygotsky, se debruça sobre a investigação rigorosa dos processos mentais internos, focando em como o sujeito ativamente percebe, organiza, interpreta, armazena e recupera as informações do mundo ao seu redor.",
  "Sob essa ótica epistemológica, o desenvolvimento é visto como uma reestruturação ativa de esquemas mentais. O sujeito não reage de forma passiva aos estímulos do meio, mas atua como um verdadeiro construtor de seu próprio conhecimento, adaptando suas estruturas cognitivas diante de novas experiências e rupturas de equilíbrio.",
  "Ao mapear os estágios do desenvolvimento cognitivo e a importância vital da mediação social e da linguagem, essa perspectiva dota o terapeuta ou educador de ferramentas cruciais para sintonizar sua comunicação ao nível de processamento do outro. Isso facilita a expansão de capacidades cognitivas e o alcance de novos patamares de autonomia intelectual. Referência: Livro: Capítulo 1 / Aula 03 / Aula 10 / Aula 13.",
  "<strong>12- Perspectiva Contextual</strong>",
  "A perspectiva contextual, cujo principal expoente é a teoria bioecológica de Urie Bronfenbrenner, defende de forma absoluta que o desenvolvimento humano ocorre de maneira integrada e indissociável, sempre imerso em múltiplos sistemas sociais e ecológicos. Sob esse prisma, o sujeito não é influenciado de forma linear e passiva, mas sim por meio de processos contínuos de interação recíproca entre suas características biológicas individuais e os diversos níveis ambientais estruturados, classificados detalhadamente em microssistema, mesossistema, exossistema, macrossistema e cronossistema.",
  "A aplicação prática dessas dinâmicas no diagnóstico comportamental permite ao terapeuta ou mentor mapear com precisão os fatores de proteção e de vulnerabilidade presentes em cada camada ecológica do sujeito. O microssistema revela o impacto das relações mais próximas, como a família e o trabalho, enquanto o cronossistema situa o indivíduo nas transformações e marcos temporais de sua própria época histórica.",
  "Dessa forma, o comportamento humano deixa de ser visto de maneira estática e isolada. Ele passa a ser profundamente compreendido como uma resposta adaptativa sistêmica a todo o seu ecossistema de relações, expandindo as possibilidades de intervenção e facilitando o desenvolvimento de soft skills e o bem-estar duradouro. Referência: Livro: Capítulo 1 / Aula 03 / Aula 12.",
  "<strong>13- Perspectiva Evolucionista / Sociobiológica</strong>",
  "A perspectiva evolucionista ou sociobiológica, profundamente inspirada nas formulações clássicas de Charles Darwin e ampliada pela moderna psicologia evolucionista, foca sua investigação científica no valor de sobrevivência e na função adaptativa de determinados comportamentos e predisposições em ambientes específicos ao longo do ciclo filogenético.",
  "De acordo com esse modelo de análise, muitas de nossas reações emocionais e soft skills fundamentais, como a empatia, o apego relacional, a cooperação social e até mesmo as respostas reflexas de luta ou fuga coordenadas pelo cérebro reptiliano, não representam construções casuais ou arbitrárias. Trata-se de adaptações filogenéticas estáveis que foram consolidadas na biologia da espécie ao longo de milhares de gerações, visando garantir a preservação da vida somática e a reprodução.",
  "Na abordagem clínica e no desenvolvimento pessoal, decodificar essas funções originais de autopreservação permite libertar o indivíduo do peso de julgamentos moralistas severos sobre seus próprios comportamentos sabotadores ou reativos. Essa compreensão científica possibilita que o neocórtex pré-frontal assuma novamente o controle voluntário e promova a regulação consciente das respostas cognitivas, emocionais e somáticas. Referência: Livro: Capítulo 1 / Aula 04 / Aula 06.",
  "<strong>14- Gênese Histórica e Epistemológica (PNUD, 1990)</strong>",
  "A gênese histórica e epistemológica do conceito contemporâneo de desenvolvimento humano, formalizada pelo Programa das Nações Unidas para o Desenvolvimento, o PNUD, a partir de seu célebre relatório de 1990, representa um marco histórico e teórico na desconstrução do modelo tradicional de progresso das nações, que até então era avaliado de forma exclusiva com base em parâmetros macroeconômicos clássicos e quantitativos.",
  "Fundamentada no pensamento de cientistas renomados como Amartya Sen e Mahbub ul Haq, essa transição de paradigmas estabelece que o verdadeiro desenvolvimento não consiste na acumulação contínua de riqueza material ou na mera produtividade industrial mecânica regulada pelo tempo cronológico de Cronos. Trata-se, ao contrário, de um processo constante de expansão das oportunidades de escolha individual e das liberdades reais que os cidadãos desfrutam para liderar a vida que genuinamente valorizam.",
  "Essa fundamentação teórica orienta de forma direta a prática do desenvolvimento comportamental e da promoção da saúde integral. Ela relembra o profissional de que o progresso existencial de um indivíduo deve ser avaliado por sua capacidade real de ação e escolha de rotinas saudáveis que nutram sua qualidade de vida. Essa visão foi o motor para a criação do próprio Índice de Desenvolvimento Humano, o IDH. Referência: Livro: Capítulo 1 / Aula 02.",
  "<strong>15- Parâmetros Macroeconômicos Clássicos (PIB, Renda Per Capita, Produtividade Industrial)</strong>",
  "Os parâmetros macroeconômicos clássicos — com destaque para o Produto Interno Bruto, o PIB, a renda per capita e as taxas de produtividade industrial — consolidaram-se, a partir da Revolução Científica e da era industrial, como os critérios hegemônicos para medir o sucesso e o progresso das nações. Essa perspectiva assentava-se no pressuposto puramente linear e mecânico de que o avanço financeiro e a capacidade de faturamento material se converteriam diretamente em bem-estar e em qualidade de vida para toda a população.",
  "No entanto, essa abordagem mecânica ignora completamente as variáveis sistêmicas que definem a existência humana. Ao focar exclusivamente no crescimento quantitativo, esse modelo trata os cidadãos como meras engrenagens de alto desempenho produtivo. Essa cobrança implacável por performance, sem o devido suporte socioemocional, resulta em um alarmante paradoxo contemporâneo: enquanto os gráficos econômicos registram recordes de produtividade, a saúde mental e coletiva entra em colapso devido à negligência sistemática em relação aos sentimentos e às emoções básicas do sujeito.",
  "Dessa forma, o entendimento crítico desses parâmetros clássicos alerta os profissionais de desenvolvimento humano e saúde integral sobre a necessidade de superar as metas puramente numéricas de Cronos. É imperativo adotar uma visão holística que integre a estabilidade psicológica e a homeostase somática como pilares inegociáveis do verdadeiro progresso existencial. Referência: Livro: Capítulo 1 / Aula 02 / Aula 08.",
  "<strong>16- Abordagem das Capacidades (Amartya Sen e Mahbub ul Haq)</strong>",
  "A Abordagem das Capacidades, formulada e defendida de forma brilhante pelos economistas Amartya Sen e Mahbub ul Haq, propõe uma ruptura radical com o determinismo econômico utilitarista ao redefinir a própria essência do desenvolvimento. Esse referencial teórico postula categoricamente que o verdadeiro progresso de um indivíduo ou de uma sociedade não deve ser avaliado pelo acúmulo de bens materiais ou pela expansão de riqueza financeira, mas sim pelo alargamento das capacidades reais das pessoas de ser e de fazer o que elas têm razões para valorizar.",
  "Nesse modelo ético e humano, o foco principal deixa de ser a utilidade mecânica dos bens para se concentrar nas oportunidades substantivas que o indivíduo de fato possui. As liberdades reais são tratadas tanto como o fim primordial quanto como o principal meio para o desenvolvimento. O ser humano é resgatado em sua condição de agente ativo de sua própria história, dotado de dignidade e autonomia para agir, e não como um mero receptor passivo de intervenções externas ou de políticas assistenciais de sobrevivência.",
  "Na prática da mentoria, da mediação de conflitos e do desenvolvimento comportamental, a abordagem das capacidades fundamenta a estruturação de caminhos que reabilitem a autoeficácia e a agência pessoal do sujeito. Ao remover bloqueios cognitivos e ambientais, ela apoia o indivíduo a expandir seu repertório de ações práticas, transformando seu potencial latente em conquistas existenciais reais. Referência: Livro: Capítulo 1 / Aula 02.",
  "<strong>17- Dimensões e Oportunidades de Escolha Individual</strong>",
  "As dimensões e as oportunidades de escolha individual constituem o núcleo operacional que viabiliza a agência pessoal e a realização do pleno potencial humano. Sob a ótica do desenvolvimento integrado, as oportunidades reais de escolha não se limitam a opções abstratas ou teóricas; elas se traduzem na liberdade fática que o sujeito possui para definir sua trajetória de vida, suas parcerias relacionais e a organização cotidiana de seu tempo existencial em Cronos e Kairós.",
  "A privação dessas escolhas ou a imposição de rotinas puramente mecânicas, dominadas pelas urgências profissionais e pelo dreno atencional, gera um estado de sofrimento crônico e alienação. Como assevera o psicólogo Mihaly Csikszentmihalyi, a repressão psicológica ou social não conduz à virtude; pelo contrário, restringe e empobrece a experiência existencial do indivíduo. A verdadeira transformação comportamental só se consolida quando o sujeito exercita seu poder de veto consciente e seleciona, de forma autônoma e disciplinada, hábitos e caminhos alinhados aos seus valores mais profundos de identidade.",
  "No contexto de liderança e mentoria sistêmica, viabilizar e nutrir esses espaços de escolha consciente permite que o colaborador ou mentorado transite do estado de reatividade para o patamar de agência pessoal. Isso ativa as funções executivas do neocórtex e estabelece as condições biológicas necessárias para o florescimento integral e o bem-estar duradouro. Referência: Livro: Capítulo 1 / Aula 02 / Aula 14 / Aula 19.",
  "<strong>18- O Pentágono da Saúde Integral</strong>",
  "O Pentágono da Saúde Integral, estruturado como um modelo sistêmico e integrador, postula que o bem-estar e a qualidade de vida do ser humano dependem diretamente do equilíbrio dinâmico e codependente de cinco dimensões vitais: a saúde física, a saúde emocional ou mental, a saúde social ou relacional, a saúde espiritual ou de propósito de vida, e a saúde profissional ou financeira. Sob essa perspectiva holística, a negligência persistente de qualquer um desses pilares gera, inevitavelmente, uma ruptura ou um desequilíbrio que compromete a integridade de todo o sistema.",
  "Na prática clínica e de mentoria, o pentágono funciona como uma poderosa ferramenta de diagnóstico e autoconhecimento, que permite mapear com precisão onde o indivíduo está sofrendo drenos de energia e de atenção. Ao identificar o pilar que se encontra em sofrimento — como o abandono das rotinas de manutenção física devido às exigências profissionais excessivas medidas pelo tempo de Cronos —, o profissional de saúde ou desenvolvimento humano consegue intervir de forma cirúrgica.",
  "Essa intervenção permite restabelecer a homeostase interna do sujeito e promover o desenvolvimento de soft skills e hábitos saudáveis, fatores essenciais para nutrir o florescimento existencial e alcançar uma vida plena. Referência: Livro: Capítulo 1 / Aula 02.",
  "<strong>19- A Natureza Tridimensional do Ser Humano</strong>",
  "A Natureza Tridimensional do Ser Humano, fundamentada na indissociabilidade epistemológica e biológica da nossa espécie, estabelece que o indivíduo é constituído, de forma integrada, por três dimensões fundamentais que operam em contínuo acoplamento estrutural: a dimensão física ou fisiológica-somática, a dimensão cognitiva ou mental-emocional, e a dimensão psicossocial ou relacional. Essa perspectiva supera de forma definitiva o dualismo cartesiano entre mente e corpo, ao demonstrar que qualquer alteração ou perda de recursos em uma dessas esferas provoca repercussões bioquímicas e funcionais imediatas nas outras duas.",
  "No campo do desenvolvimento comportamental, esse modelo teórico orienta o terapeuta ou o mentor a evitar a análise de queixas ou de sintomas de maneira isolada. Uma dor física crônica, por exemplo, atrofia as capacidades de regulação emocional coordenadas pelo neocórtex pré-frontal e sabota a qualidade dos contatos interpessoais, o que acaba gerando isolamento psicossocial.",
  "Dessa forma, compreender essa tridimensionalidade essencial possibilita desenhar estratégias de intervenção integradas. Nelas, a ativação voluntária do neocórtex e o preenchimento do tanque de afeto relacional atuam em perfeita sinergia para resgatar a homeostase somática e o equilíbrio geral do sujeito. Referência: Livro: Capítulo 1 / Aula 03.",
  "<strong>20- Dimensão Física (Fisiológica e Somática)</strong>",
  "A dimensão física, que engloba os aspectos fisiológicos e somáticos do organismo, constitui a base biológica concreta sobre a qual se apoiam todos os processos cognitivos e relacionais do ser humano. Essa dimensão é coordenada de forma direta e autônoma pelo tronco encefálico e pelas vias subcorticais do sistema nervoso central, sendo a responsável máxima pela regulação de funções vitais básicas, como a respiração pulmonar, os batimentos cardíacos somáticos, o sono reparador de ondas lentas, a digestão alimentar e a manutenção da imunidade celular.",
  "A negligência crônica em relação ao corpo — manifestada pelo sedentarismo prolongado, pela privação de sono profundo e pelo estresse inescapável que inunda o sistema com cortisol — gera uma atrofia funcional que drena os recursos de glicose e oxigênio do neocórtex pré-frontal. Esse processo induz o sujeito a um estado de desamparo aprendido e de reatividade límbico-reptiliana constante.",
  "Na prática de promoção da saúde integral, reabilitar essa dimensão exige a implementação voluntária de rotinas de exercício físico regular, nutrição celular de qualidade e descanso estratégico organizados na agenda de Cronos. Essa disciplina livremente escolhida permite restaurar a homeostase biológica e viabilizar o pleno florescimento das soft skills e da agência pessoal. Referência: Livro: Capítulo 1 / Aula 02 / Aula 03 / Aula 07.",
  "<strong>21- Dimensões Cognitivas (Processos Mentais Superiores e Regulação Emocional)</strong>",
  "A dimensão cognitiva, estruturada em torno dos processos mentais superiores, compreende as sofisticadas operações de atenção seletiva, memória de longo prazo, raciocínio lógico-linear e tomadas de decisão, as quais são coordenadas pelo neocórtex pré-frontal. Essa esfera de processamento é a responsável direta por traduzir os estímulos multissensoriais em conceitos abstratos, permitindo ao sujeito interpretar a realidade e planejar suas ações futuras com autonomia técnica.",
  "Além do processamento puramente lógico, essa dimensão engloba os complexos mecanismos de regulação emocional e o exercício do veto cognitivo. Quando o sistema límbico, hiperestimulado por ameaças ou conflitos, tenta sequestrar a energia do cérebro, cabe ao neocórtex intervir de forma eferente e inibitória, acalmando o alarme da amígdala e restaurando o controle analítico sobre as reações comportamentais.",
  "Nas práticas de mentoria e desenvolvimento comportamental, o fortalecimento dessa dimensão auxilia o sujeito a realizar a transição de um estado de reatividade límbica cega para um patamar de agência pessoal lúcida. Ao dominar seus próprios processos cognitivos, o indivíduo conquista a plasticidade neural necessária para aprender de forma acelerada e consolidar novos hábitos de alta performance. Referência: Aula 04 / Aula 05 / Aula 07 / Aula 10.",
  "<strong>22- Dimensão Psicossocial (Relações Interpessoais e Integração Comunitária)</strong>",
  "A dimensão psicossocial abrange toda a teia de relações interpessoais, conexões afetivas e processos de integração comunitária que conectam o sujeito ao seu meio social envolvente. Epistemologicamente indissociável das esferas somática e cognitiva, essa dimensão baseia-se em nossa necessidade neurobiológica inata de pertencimento psicológico, segurança relacional e validação mútua por meio dos laços de afeto.",
  "A calibração fina dessa dimensão depende da ativação harmoniosa dos neurônios-espelho e da capacidade de estabelecer conexões profundas de rapport e sintonia empática, como as descritas nas cinco linguagens do amor de Gary Chapman. Relações interpessoais saudáveis funcionam como potentes reguladores descendentes do estresse fisiológico, preenchendo o tanque emocional e desarmando as reatividades de defesa do cérebro primitivo.",
  "Por outro lado, o isolamento social crônico ou o litígio sistemático sabotam as capacidades cognitivas do sujeito, gerando uma inundação constante de cortisol que atrofia os processos regenerativos da vida somática. Assim, nutrir laços psicossociais de alta qualidade relacional é um pilar vital para o desenvolvimento humano integral, a saúde mental e o florescimento existencial sustentável. Referência: Livro: Capítulo 1 / Aula 11 / Aula 12 / Aula 17 / Aula 21.",
  "<strong>23- Desenvolvimento Ontogenético</strong>",
  "O desenvolvimento ontogenético refere-se à história evolutiva e de maturação do indivíduo ao longo de todo o seu ciclo vital, operando em contínuo acoplamento estrutural com as exigências e transformações do meio social. Diferentemente da evolução filogenética da espécie, a ontogênese debruça-se sobre as transformações quantitativas e qualitativas particulares de um sujeito único, cujas etapas cronológicas de desenvolvimento físico, cognitivo e psicossocial se desdobram sob o impaciente ritmo temporal de Cronos, que dita o ritmo natural do envelhecimento somático.",
  "Trata-se, portanto, do desdobramento ativo da programação biológica da própria espécie, que é vivida de forma inteiramente única na história de cada sujeito concreto. Essa trajetória biológica se estende desde o exato instante em que ocorre a fusão celular dos gametas dos progenitores, atravessa todas as fases de maturação cortical e segue até o encerramento biológico de todas as funções vitais.",
  "No mapeamento clínico e na intervenção existencial, o real entendimento da ontogênese constitui a chave para mitigar todo o sofrimento decorrente de nossa resistência psicológica às regras inflexíveis da biologia. Essa tomada de consciência ampara o indivíduo a aceitar o envelhecimento saudável do corpo, direcionando sua energia para o desenvolvimento de seu legado. Referência: Aula 03 / Aula 14."
]

OUTPUT_DIR = "public/audio"
OUTPUT_MP3 = os.path.join(OUTPUT_DIR, "modulo1-intro.mp3")
OUTPUT_JSON = os.path.join(OUTPUT_DIR, "modulo1-intro-tempos.json")

def limpar_html(texto):
    t = re.sub(r'<[^>]+>', '', texto)
    return t.strip()

async def gerar():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    timestamps = []
    tempo_acumulado = 0.0

    print(f"\n🎙️ Gerando áudio da Intro com a voz neural...")

    temp_files = []
    with open(OUTPUT_MP3, "wb") as master_audio:
        for i, raw_text in enumerate(PARAGRAFOS):
            texto_limpo = limpar_html(raw_text)
            temp_chunk = f"temp_chunk_intro_{i}.mp3"

            communicate = edge_tts.Communicate(texto_limpo, VOZ_SELECIONADA)
            await communicate.save(temp_chunk)

            audio_info = MP3(temp_chunk).info
            duracao = audio_info.length

            inicio = round(tempo_acumulado, 2)
            fim = round(tempo_acumulado + duracao, 2)

            timestamps.append({
                "index": i,
                "start": inicio,
                "end": fim
            })

            tempo_acumulado += duracao

            with open(temp_chunk, "rb") as f_chunk:
                master_audio.write(f_chunk.read())

            temp_files.append(temp_chunk)
            print(f"  ✓ Parágrafo {i + 1}/{len(PARAGRAFOS)} processado")

    for f in temp_files:
        if os.path.exists(f):
            os.remove(f)

    with open(OUTPUT_JSON, "w", encoding="utf-8") as jf:
        json.dump(timestamps, jf, indent=2, ensure_ascii=False)

    print("\n✅ Intro concluída com sucesso!")
    print(f"-> Arquivo MP3: {OUTPUT_MP3}")
    print(f"-> Arquivo de Tempos: {OUTPUT_JSON}\n")

if __name__ == "__main__":
    asyncio.run(gerar())